<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'db',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'mautic',
	'db_user' => 'mautic',
	'db_password' => 'dipb7KgRZnQGcswzhVqByEB29JLg',
	'db_backup_tables' => 1,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.7.23',
	'mailer_from_name' => 'Mark Mulder',
	'mailer_from_email' => 'mark@bsolut.com',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => 'mark@bsolut.com',
	'mailer_password' => '',
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '759b780fb271c632799780aba0256cbc615b437835907a71fa556938574be32c',
	'site_url' => 'http://localhost',
);
